"""Policy evaluation engine.

Checks plan inputs against predefined security policy rules before executing
any system operations.
"""

from __future__ import annotations

from typing import Any

from app.core.logger import RequestLogger
from app.models.policy_decision import PolicyDecision
from app.policy.risk import RiskLevel
from app.policy.rules import POLICY_RULES

logger = RequestLogger("SentinelAI.PolicyEngine")


class PolicyEngine:
    """Evaluates planned intents against safety parameters and risk profiles."""

    def evaluate(self, plan: Any) -> PolicyDecision:
        """Evaluate safety rules for the proposed execution plan.

        Args:
            plan: The Plan generated by the planning strategy.

        Returns:
            A PolicyDecision indicating allowed, risk level, and confirmation.
        """
        logger.info("Evaluating plan: intent='%s', tool='%s'", plan.intent, plan.tool)

        rule = POLICY_RULES.get(plan.intent)

        if rule is None:
            decision = PolicyDecision(
                allowed=False,
                risk=RiskLevel.CRITICAL,
                confirmation_required=False,
                reason=f"No policy found for intent '{plan.intent}'",
            )
            logger.warning(
                "Policy Denied: No rule defined for intent '%s'. Blocked with CRITICAL risk.",
                plan.intent,
            )
            return decision

        decision = PolicyDecision(
            allowed=rule["allowed"],
            risk=rule["risk"],
            confirmation_required=rule["confirmation"],
        )

        if not decision.allowed:
            logger.warning(
                "Policy Denied: intent='%s' is blocked. Risk=%s",
                plan.intent,
                decision.risk.value,
            )
        elif decision.confirmation_required:
            logger.info(
                "Policy Conditional: intent='%s' requires confirmation. Risk=%s",
                plan.intent,
                decision.risk.value,
            )
        else:
            logger.info("Policy Allowed: intent='%s' passes check. Risk=%s", plan.intent, decision.risk.value)

        return decision